### ISSUE TITLE
feat: comments

### ISSUE THREAD

**Issue by akhileshthite** [BLOOP-browser/bloop-browser-extension#4]
Comments option on the top right corner of a blip/link.

### Behaviour:
- A user clicks on "Comment" option on a blip.
- Bloop redirects the user to comments page.
- A comment box will contain a timestamp in the left corner, below which will be the userID and text. Additionally, there will be a text input field at the bottom of the page and a button to submit a new comment.

### TODOs:
- [ ] Create a new "comment-search" dir in `./src/Components/` with new `comment-search.tsx` and `comment-search.css`
  - [ ] A comment should have `id`, `userId`, `text`, and `createAt` props (refer to the [comment.ts](https://github.com/BLOOP-browser/bloop-browser-extension/blob/main/src/models/comment.ts) in `./src/models`).
  - [ ] Comments component UI should be same as the [link-search.tsx](https://github.com/BLOOP-browser/bloop-browser-extension/blob/main/src/Components/Link-search/link-search.tsx) component.
- [ ] Create a new "comments-page" dir in `./src/pages/` with new `comments-page.tsx` and `comments-page.css` files.
  - [ ] Please refer to the [comment-service.ts](https://github.com/BLOOP-browser/bloop-browser-extension/blob/main/src/services/comment-service.ts) in `./src/services/` to create a comment in the blip (`createLinkComment`) and to get the comments from a particular blip (`getLinkComments`).
  - [ ] Make sure to integrate this in `comments-page.tsx` (see how the links are fetched from a particular list in [link-search.tsx](https://github.com/BLOOP-browser/bloop-browser-extension/blob/main/src/Components/Link-search/link-search.tsx) with `link-service.tsx`).
    - [ ] Create an input field and a submit button which will add a new comment with the help of `createLinkComment` function.
  - [ ]  Update the main `App.tsx` file with the comments-page.tsx updates.
- [ ] Create a Comments option on [links component](https://github.com/BLOOP-browser/bloop-browser-extension/blob/6266a2aaacb6822a35be99c8fe925f6eef3e03d8/src/Components/Link-search/link-search.tsx#L70) which will redirect to the comments-page.
